package errors

import "errors"

var (
	ErrInvalidInput     = errors.New("invalid input provided")
	ErrEmptyInput       = errors.New("input is empty")
	ErrOutOfRange       = errors.New("value is out of the allowed range")
	ErrNotFound         = errors.New("resource not found")
	ErrAlreadyExists    = errors.New("resource already exists")
	ErrNotAllowed       = errors.New("operation not allowed")
	ErrUnauthorized     = errors.New("unauthorized access")
	ErrForbidden        = errors.New("access is forbidden")
	ErrSessionExpired   = errors.New("user session has expired")
	ErrTokenExpired     = errors.New("authentication token has expired")
	ErrTokenInvalid     = errors.New("invalid authentication token")
	ErrUserSuspended    = errors.New("user account is suspended")
	ErrPasswordMismatch = errors.New("password mismatch")
	ErrRateLimit        = errors.New("rate limit exceeded")
	ErrQuotaExceeded    = errors.New("quota exceeded")
	ErrInvalidEmail     = errors.New("invalid email address")
	ErrInvalidURL       = errors.New("invalid URL")
	ErrInvalidDate      = errors.New("invalid date")
	ErrDatabase         = errors.New("database error")
	ErrCache            = errors.New("cache error")
	ErrExternalService  = errors.New("external service error")
	ErrTimeout          = errors.New("operation timeout")
	ErrTooManyRequests  = errors.New("too many requests")
	ErrInvalidFileType  = errors.New("invalid file type")
	ErrFileSizeExceeded = errors.New("file size exceeded")
	ErrFileNotFound     = errors.New("file not found")
	ErrEncryption       = errors.New("encryption error")
	ErrDecryption       = errors.New("decryption error")
	ErrAPIKeyInvalid    = errors.New("invalid API key")
	ErrConcurrency      = errors.New("concurrent modification detected")
	ErrUnsupported      = errors.New("unsupported operation")
)

var (
	ErrEmailNotVerified      = errors.New("email not verified")
	ErrInvalidCredentials    = errors.New("invalid credentials")
	ErrPasswordTooWeak       = errors.New("password too weak")
	ErrDuplicateEntry        = errors.New("duplicate entry")
	ErrInvalidConfiguration  = errors.New("invalid configuration")
	ErrInternalServer        = errors.New("internal server error")
	ErrResourceUnavailable   = errors.New("resource unavailable")
	ErrOperationAborted      = errors.New("operation aborted")
	ErrInvalidJSON           = errors.New("invalid JSON")
	ErrSchemaValidation      = errors.New("schema validation error")
	ErrInvalidCSV            = errors.New("invalid CSV")
	ErrInvalidXML            = errors.New("invalid XML")
	ErrInvalidFileExtension  = errors.New("invalid file extension")
	ErrFileUploadFailed      = errors.New("file upload failed")
	ErrFileDownloadFailed    = errors.New("file download failed")
	ErrDataInconsistency     = errors.New("data inconsistency")
	ErrDataTypeMismatch      = errors.New("data type mismatch")
	ErrResourceLocked        = errors.New("resource locked")
	ErrResourceLimitExceeded = errors.New("resource limit exceeded")
	ErrOperationNotSupported = errors.New("operation not supported")
	ErrTemporaryUnavailable  = errors.New("temporary unavailable")
	ErrThirdPartyIntegration = errors.New("third-party integration error")
)
